#!/usr/bin/env bash
#  This script defines a function that perfoms a DNS lookup on a given domain.
#+ It then runs the func to display the information in a specified format.
#
#  The function takes 2 arguments:
#+      a. domain(str) - mandatory argument for the domain name to be queried.
#+      b. subdomain(str) - optional argument to specify a sub/d to be requested.
# Usage: ./0-world_wide_web <domain> [<subdomain name>]

function dns_lookup {
    answer_sect=$(dig "$2"."$1" +noall +answer | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $answer_sect" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_lookup "$1" "www"
  dns_lookup "$1" "lb-01"
  dns_lookup "$1" "web-01"
  dns_lookup "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_lookup "$1" "$2"
else
	echo -e '\033[0;33mPlease provide a domain!' # Coloured output
        echo -e '\033[0;34mUsage:\033[0m ./0-world_wide_web <domain> [<subdomain name>]' # Coloured output
fi
