#!/usr/bin/env bash
# This script transfers a file from our client to a server.
# Its usage is: 0-transfer_file <PATH_TO_FILE> <IP> <USERNAME> <PATH_TO_SSH_KEY>.

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
scp -i "$4" "$1" "$3"@"$2":~/
