#!/usr/bin/env bash
# Confingures a new Ubuntu machine based on specified configurations
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!\n" > /var/www/html/index.html
service nginx start
