#!/usr/bin/env bash
# Confingures a new Ubuntu machine with redirection commands
apt-get update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configuration for redirection on server
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT
server {
    listen 80;
    server_name kaygeea.tech;

    location / {
        return 301 https://new_domain.com\$request_uri;
    }
}
EOT

# Configuration for Page Not Found 404 error
sudo tee /var/www/html/404.html > /dev/null <<EOT
<!DOCTYPE html>
<html>
<head>
    <title>404 - Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page.</h1>
</body>
</html>
EOT

service nginx restart
