#!/usr/bin/env bash
# This script configures a new Ubuntu machine based on the following requirements:
#     a. Adds a custom header to the response header named - "X-Served-By"
#     b. The value of the custom header will be set to the server that nginx runs a request on.
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
# Create necessary directories and set permissions
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www

# Create index and 404 pages
echo 'Hello World!' | sudo tee /var/www/html/index.html >/dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html >/dev/null

# Configure Nginx with custom header
server_config=$(cat <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://youtube.com permanent;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF
)

echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default >/dev/null

# Restart Nginx service
sudo service nginx restart
