#!/usr/bin/env bash
# This script configures a new Ubuntu machine based on the following requirements:
#    a. Install & configure HAproxy so that it sends traffic to web-01 and web-02.
#    b. Set up HAproxy so it can be managed via an init script.
#    c. Set up HAproxy to distribute requests using a roundrobin algorithm
# NOTE: By default, requests are sent to the pool of servers using round-robin load-balancing;
#	as such it does not need to be stated explicitly.

# Install HAproxy version 2.7-stable
# apt-get -y install --no-install-recommends software-properties-common
# add-apt-repository ppa:vbernat/haproxy-2.7
# apt-get -y install haproxy=2.7.\*

sudo apt update
sudo apt-get -y install haproxy

# Configure HAproxy so that it sends traffic to web-01 & web-02
haproxy_config=$(cat <<EOF

frontend server-frontend
        mode http
        bind *:80
        default_backend server-backend

backend server-backend
        mode http
        option httpchk
        server web-01 52.207.189.239:80 check
	server web-02 52.87.8.248:80 check
EOF
)

echo "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be managed by an init script
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart
