#!/usr/bin/env bash
# This script configures a new Ubuntu machine based on the following requirements:
#    a. Install & configure HAproxy so that it sends traffic to web-01 and web-02.
#    b. Set up HAproxy so it can be managed via an init script.
#    c. Set up HAproxy to distribute requests using a roundrobin algorithm
# NOTE: By default, requests are sent to the pool of servers using round-robin load-balancing;
#	as such it does not need to be stated explicitly.

# Install HAproxy version 2.7-stable
# apt-get -y install --no-install-recommends software-properties-common
# add-apt-repository ppa:vbernat/haproxy-2.7
# apt-get -y install haproxy=2.7.\*

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  ehoneah-frontend
        bind *:80
        mode http
        default_backend ehoneah-backend
backend ehoneah-backend
        balance roundrobin
        server 212173-web-01 100.25.19.204:80 check
        server 212173-web-02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
