#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it.
#
# The script takes one argument - the password used to connect to the MySQL database.

# Create MySQL dump
mysqldump -u root -p "$1" --all-databases > backup.sql

# Archive and compress the dump file created
tar -czf $(date +%d-%m-%Y).tar.gz
