#!/usr/bin/env bash
# This script displays numbers from 1 to 100 in a list format
# Specs:
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number

iter=100

for (( i=1; i <= iter; i++ )); do
	if ((i % 3 == 0 && i % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
