#!/usr/bin/env bash
#This script displays a string 10 times, using a while loop

n=0

while [ $n -lt 10 ]
do
	if ((n == 3 ))
	then
		echo "bad luck"
	elif ((n == 7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n+1))
done
