#!/usr/bin/env bash
#This script displays a string 10 times, using a while loop

n=0

while [ $n -lt 10 ]; do
	n=$((n+1))
	if ((n == 4))
	then
		echo "bad luck"
		continue
	elif ((n == 8))
	then
		echo "good luck"
		continue
	fi
	echo "Best school"
done
