#!/usr/bin/env bash
#This script displays a string 10 times, using a while loop

n=1

while [ $n -le 10 ]; do
	n=$((n+1))
	if ((n == 5))
	then
		echo "bad luck"
		continue
	elif ((n == 9))
	then
		echo "good luck"
		continue
	fi
	echo "Best school"
done
