#!/usr/bin/env bash
# This script displays numbers from 1-20 and:
# displays 4 and then "bad luck from China" for the 4th loop iteration
# displays 9 and then "bad luck from Japan" for the 9th loop iteration
# displays 17 and then "bad luck from Italy" for the 17th loop iteration

n=0

while [ $n -lt 20 ]; do
	n=$((n+1))
	case $n in
		4) echo "$n"; echo "bad luck from China";;
		9) echo "$n"; echo "bad luck from Japan";;
		17) echo "$n"; echo "bad luck from Italy";;
		*) echo  "$n"
	esac
done
