#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# Specs:
# 	Display hours from 0 - 12
#	Display minutes from 1 - 59

hrs=0

while [ $hrs -le 12 ]
do
  echo "Hour: $hrs"
  mins=1
  while [ $mins -le 59 ]
  do
    echo "$mins"
    (( mins++ ))
  done
  (( hrs++ ))
done
